# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='infection_rate',
        ),
        migrations.AddField(
            model_name='location',
            name='matches_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='matches_lost',
            field=models.IntegerField(default=0),
        ),
    ]
