# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20161202_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='matches_lost',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='matches_won',
            field=models.IntegerField(default=70),
        ),
    ]
