# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20161202_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(max_length=200)),
                ('antidotes_given_out', models.IntegerField(default=0)),
            ],
        ),
    ]
