# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_safezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_antidotes',
            field=models.IntegerField(default=0),
        ),
    ]
