# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_profile_num_antidotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zone_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
