# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20161212_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='safezone',
            name='num_antidotes_in_stock',
            field=models.IntegerField(default=25),
        ),
    ]
