# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_safezone_num_antidotes_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safezone',
            old_name='num_antidotes_in_stock',
            new_name='antidotes_in_stock',
        ),
    ]
