# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20161223_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='safezone',
            name='zone_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
